version: "3.5"

services:
  codeshovel-web:
    build:
      args:
        - "SERVER_ADDRESS=${PUBLICHOSTNAME}"
        - "PUBLIC_ADDRESS=${PUBLICHOSTNAME}"
      context: ./codeshovel-webservice
    expose:
      - 8080
    restart: always
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - "${CODESHOVEL_LOG_PATH}:/requests.csv"
      - "${CODESHOVEL_CACHE_PATH}:/cache"
    ports:
      - "8080:8080"
